apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: nexora
type: Opaque
stringData:
  mysql-root-password: RootPass123!
  mysql-password: StrongPass123!
  mysql-user: wpuser
  mysql-database: wordpress
